# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TR01OJ8EqLeMOoUTuGSoQ1xo4ceMCnly

**Homework 1: Basic Markdown, Python Variables, Math Operations, User Input, and PEMDAS**

1. Show what Markdown is used for in Jupyter Notebooks
"""

# Markdown is used to format documentation in the text cells, for instance to bold or italicize or change font size

"""2. Show how to format text to be bold in Markdown. Provide an example."""

## You format bold text by surrounding the text with a double asteriks

**This text will be bolded**

"""3. Create a Python variable named 'a' and assigne it the value 5"""

a=5
print(a)

"""4. Perfom an addition operation with any two numbers and display the result"""

a=5
b=4
print(a+b)

"""5. Divide 15 by 3 and show the result"""

print(15/3)

"""6. Use the 'input()' function to ask the user for thier name and then greet them"""

name = input("What is your name? ")
print("Hello,", name)

"""7. Calculate the square of 7 and display the result"""

print(7**2)

"""8. Ask the user for a number, multiply it by 2, and displat the result"""

x= float(input("Provide a number: "))
print(x*2)

"""9. Write a program that converts time from hours to seconds. Ask the user to input the time in hours, and then convert that time into seconds. Remember 1 hour equals 3600 seconds."""

hr = float(input("Tell us the time in hours: "))
conv_factor = hr*3600
print("The time in seconds is: ", conv_factor)

"""10. Evaluate the expression '3 * (4 + 5) - 6 / 2' and display the result"""

print(3*(4+5)-6/2)

"""11. Assign the string 'Python to a variable and print it"""

language = "Python"
print(language)

"""12. Calculate the remainder when 22 is divided by 5"""

remainder = 22%5
print(remainder)

"""13. Ask the user for tow numbers, add them together, and display the sum"""

x = float(input("Provide a number: "))
y = float(input("Provide a second number: "))
print("Those numbers added together is: ", x+y)

"""14. Write a Python code snippet that takes user input and print the type of the unput variable"""

x = input("Provide a number: ")
print(type(x))

"""15. Calculate the product of 8 and 12, then subtract 4 and display the result"""

a=4
b=8
c=12

print(b*c-a)

"""16. Explain the difference between '==' and '=' in Python"""

## using = assigns a variable
## using == is Boolean and only tells if something is true or false

x=4
y=3
x==y

"""17. Use Python to find the floor division of 100 by 11"""

100//11

"""18. Ask the user for a number, then calculate the square of that number"""

num1= float(input("Provide a number: "))
print(num1**2)

"""19. What does the '%' operator doin in Python? Provide and example."""

## The % operator takes the remainder of a division operation and displays it

100%3

"""20. Using variables, demonstrate how to calculate and print hte area of a rectangle"""

length = 10
width = 5
area = length*width
print(area)

